"""Backend contract consumed by the simulator-independent environment lifecycle."""

from __future__ import annotations

from typing import Any, Protocol

from purerl.config.env import EnvCfg


class SimulationBackend(Protocol):
    """Batched simulator operations required by ``BaseVecEnv``."""

    num_envs: int
    device: str
    state: Any
    all_env_ids: Any

    def initialize(self, cfg: EnvCfg) -> None: ...

    def zeros(self, shape: tuple[int, ...], *, dtype: str) -> Any: ...

    def set_joint_position_targets(self, targets: Any) -> None: ...

    def simulate(self, *, render: bool) -> None: ...

    def refresh(self) -> None: ...

    def get_net_contact_forces(self) -> Any: ...

    def sample_terrain_heights(self, world_points_xy: Any) -> Any: ...

    def set_terrain_levels(self, env_ids: Any, levels: Any) -> None: ...

    def randomize_body_properties(self, env_ids: Any, mass_delta: Any, com_offset: Any) -> None: ...

    def set_actuator_gains(self, env_ids: Any, stiffness_scale: Any, damping_scale: Any) -> None: ...

    def randomize_reset_state(
        self, env_ids: Any, root_xy: Any, root_yaw: Any, joint_position_scale: Any
    ) -> None: ...

    def apply_root_wrench(self, env_ids: Any, forces: Any, torques: Any) -> None: ...

    def add_root_velocity(self, env_ids: Any, linear_velocity_xy: Any) -> None: ...

    def reset(self, env_ids: Any) -> None: ...

    def nonzero(self, mask: Any) -> Any: ...

    def clone(self, value: Any) -> Any: ...

    def close(self) -> None: ...
