class_name: OnPolicyRunner
seed: 5
device: cuda:0
num_steps_per_env: 60
max_iterations: 10001
save_interval: 1000
experiment_name: tienkung_flat
run_name: ''
obs_groups:
  policy: [policy]
  critic: [policy]
clip_actions: null
min_action_noise_std: 0.05
max_action_noise_std: 3.0
max_checkpoint_noise_std: 3.0
logger: wandb
wandb_project: purerl
wandb_entity: null
wandb_mode: online
wandb_tags: []
wandb_run_id: null
wandb_resume: never
neptune_project: purerl
resume: false
load_run: .*
load_checkpoint: model_.*.pt
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  actor_obs_normalization: true
  critic_obs_normalization: true
  actor_hidden_dims: [512, 256, 128]
  critic_hidden_dims: [768, 256, 128]
  activation: elu
algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.001
  num_learning_epochs: 2
  num_mini_batches: 4
  learning_rate: 1.0e-5
  schedule: adaptive
  gamma: 0.994
  lam: 0.9
  desired_kl: 0.01
  max_grad_norm: 1.0
